import {useEffect,useRef,useState} from'react';import{motion,useScroll,useTransform}from'framer-motion';import{ArrowDown,ArrowRight,Check,Menu,Plus,X}from'lucide-react';import{Reveal}from'./components/Reveal';import machine from'./assets/retroexcavadora.png';
const services=[['01','Alquiler de maquinaria','Equipos listos para operar, con respaldo técnico y planes flexibles.'],['02','Movimiento de tierras','Excavación, nivelación y preparación de terrenos con precisión.'],['03','Mantenimiento experto','Servicio preventivo y respuesta en campo para que tu operación no se detenga.']];
export default function App(){const[menu,setMenu]=useState(false),[solid,setSolid]=useState(false),journey=useRef<HTMLElement>(null);const{scrollYProgress:p}=useScroll({target:journey,offset:['start start','end end']}),x=useTransform(p,[0,.25,.7,1],['55vw','5vw','-5vw','-48vw']),y=useTransform(p,[0,.4,1],['20vh','5vh','10vh']),scale=useTransform(p,[0,.3,.72,1],[.68,.95,1.08,.76]);useEffect(()=>{const f=()=>setSolid(scrollY>40);addEventListener('scroll',f,{passive:true});return()=>removeEventListener('scroll',f)},[]);return <div>
<header className={'nav '+(solid?'solid':'')}><a className="logo" href="#inicio"><b>C</b> CASYCO <small>MAQUINARIA</small></a><nav><a href="#empresa">Empresa</a><a href="#servicios">Servicios</a><a href="#equipos">Equipos</a></nav><a className="btn" href="#contacto">Cotizar proyecto <ArrowRight/></a><button onClick={()=>setMenu(true)}><Menu/></button></header>
{menu&&<motion.div className="mobile" initial={{y:'-100%'}} animate={{y:0}}><button onClick={()=>setMenu(false)}><X/></button>{['Empresa','Servicios','Contacto'].map(v=><a href={'#'+v.toLowerCase()} onClick={()=>setMenu(false)}>{v}</a>)}</motion.div>}
<main><section className="hero" id="inicio"><div className="grid"/><motion.div className="heroCopy" initial={{opacity:0,y:50}} animate={{opacity:1,y:0}} transition={{duration:.9}}><p className="tag">— Ingeniería que mueve el país</p><h1>Potencia para<br/>construir <em>futuro.</em></h1><p>Maquinaria pesada, soporte especializado y la experiencia que tu proyecto necesita para avanzar.</p></motion.div><motion.img src={machine} initial={{opacity:0,x:'35%',scale:.8}} animate={{opacity:1,x:0,scale:1}} transition={{duration:1.3}}/><a className="scroll" href="#empresa"><ArrowDown/> Descubre cómo trabajamos</a><div className="stat"><b>15+</b><span>Años moviendo<br/>grandes proyectos</span></div></section>
<section className="intro" id="empresa"><Reveal><p className="label">01 — Nuestra fuerza</p><h2>No entregamos solo máquinas.<br/><span>Entregamos capacidad.</span></h2></Reveal><div className="introText"><Reveal><p>Combinamos equipos confiables, operadores expertos y respuesta técnica en campo para mantener cada proyecto en movimiento.</p></Reveal><Reveal><a href="#servicios">Conoce nuestra empresa <ArrowRight/></a></Reveal></div></section>
<section className="journey" id="equipos" ref={journey}><div className="sticky"><div className="grid"/><motion.div className="scene s1" style={{opacity:useTransform(p,[0,.08,.27,.36],[0,1,1,0])}}><p className="label">02 — Equipo destacado</p><h2>Hecha para<br/><em>rendir.</em></h2></motion.div><motion.div className="scene s2" style={{opacity:useTransform(p,[.34,.45,.64,.73],[0,1,1,0]),y:useTransform(p,[.34,.5],[60,0])}}><b>4×4</b><h3>Control total<br/>en cada terreno.</h3><p>Tracción, estabilidad y potencia hidráulica donde otros se detienen.</p></motion.div><motion.div className="scene s3" style={{opacity:useTransform(p,[.7,.8,.96],[0,1,1]),y:useTransform(p,[.7,.85],[60,0])}}><p className="label">Siempre disponible</p><h3>Una máquina.<br/>Posibilidades infinitas.</h3><a href="#contacto">Solicitar disponibilidad <ArrowRight/></a></motion.div><motion.img className="moving" src={machine} style={{x,y,scale}}/><div className="ground"><motion.i style={{scaleX:p}}/></div><motion.small>{useTransform(p,v=>String(Math.round(v*100)).padStart(2,'0')+'%')}</motion.small></div></section>
<section className="services" id="servicios"><Reveal><p className="label">03 — Soluciones</p><h2>Todo lo que tu obra<br/>necesita para <em>avanzar.</em></h2></Reveal><div className="list">{services.map(([n,t,d])=><Reveal key={n}><article><span>{n}</span><h3>{t}</h3><p>{d}</p><ArrowRight/></article></Reveal>)}</div></section>
<section className="numbers"><p className="label">Resultados en terreno</p><div>{[['98%','Disponibilidad operativa'],['24/7','Respuesta técnica'],['120+','Proyectos ejecutados']].map(v=><Reveal><strong>{v[0]}</strong><span>{v[1]}</span></Reveal>)}</div></section>
<section className="fleet" id="flota"><Reveal><p className="label">04 — Nuestra flota</p><h2>El equipo correcto.<br/><em>Para cada desafío.</em></h2></Reveal><div className="fleetGrid">{['Retroexcavadoras','Excavadoras','Cargadores','Compactación'].map((v,i)=><Reveal><article><div className="imageSlot">IMAGEN EQUIPO 0{i+1}</div><small>0{i+1}</small><h3>{v}</h3><p>Potencia, disponibilidad y respaldo en campo.</p><ArrowRight/></article></Reveal>)}</div></section>
<section className="process"><Reveal><p className="label">05 — Así trabajamos</p><h2>De la necesidad a la <em>ejecución.</em></h2></Reveal><div className="processGrid">{[['01','Diagnóstico'],['02','Selección'],['03','Despliegue'],['04','Respaldo']].map(v=><Reveal><article><b>{v[0]}</b><Check/><h3>{v[1]}</h3><p>Coordinamos cada detalle para mantener tu proyecto avanzando.</p></article></Reveal>)}</div></section>
<section className="projects" id="proyectos"><Reveal><p className="label">06 — Proyectos</p><h2>Trabajo que deja <em>huella.</em></h2></Reveal><div className="projectGrid">{['Movimiento de 85.000 m³ de terreno','Preparación integral de plataforma','Excavación y adecuación de vías'].map((v,i)=><Reveal><article className={!i?'big':''}><div className="imageSlot">IMAGEN PROYECTO 0{i+1}</div><small>Proyecto ejecutado · Colombia</small><h3>{v}</h3></article></Reveal>)}</div></section>
<section className="why"><Reveal><p className="label">07 — Por qué Casyco</p><h2>Respaldo que se siente en la obra.</h2></Reveal><div>{['Equipos certificados y mantenidos','Operadores con experiencia','Asistencia técnica en campo','Planes flexibles por proyecto'].map((v,i)=><Reveal><p><span>0{i+1}</span>{v}<Check/></p></Reveal>)}</div></section>
<section className="testimonial"><Reveal><b>“</b><blockquote>El acompañamiento técnico hizo la diferencia. Mantuvimos el cronograma sin interrupciones.</blockquote><p>Director de obra — Proyecto vial regional</p></Reveal></section>
<section className="faq"><Reveal><p className="label">08 — Preguntas frecuentes</p><h2>Información <em>clara.</em></h2></Reveal><div>{['¿Qué zonas cubre Casyco?','¿Los equipos incluyen operador?','¿Cómo solicito una cotización?','¿Ofrecen soporte durante la obra?'].map((v,i)=><details open={i===0}><summary>{v}<Plus/></summary><p>Revisamos las condiciones específicas de tu proyecto y respondemos con una solución clara y rápida.</p></details>)}</div></section>
<section className="lead"><Reveal><p className="label">09 — Inicia tu proyecto</p><h2>Cuéntanos qué necesitas mover.</h2><p>Déjanos tus datos y nuestro equipo se comunicará contigo.</p></Reveal><form><label>Nombre<input required placeholder="Tu nombre"/></label><label>Empresa<input placeholder="Nombre de empresa"/></label><label>Correo<input type="email" required placeholder="correo@empresa.com"/></label><label>Teléfono<input type="tel" placeholder="+57 300 000 0000"/></label><label className="wide">Proyecto<textarea rows={4} placeholder="Tipo de obra, ubicación y equipo requerido"/></label><button>Solicitar cotización <ArrowRight/></button></form></section>
<section className="contact" id="contacto"><Reveal><p className="label">10 — Hablemos</p><h2>Tu obra no espera.<br/><em>Nosotros tampoco.</em></h2><a href="mailto:proyectos@casyco.com">proyectos@casyco.com <ArrowRight/></a></Reveal><footer><div className="logo"><b>C</b> CASYCO</div><p>Servicios · Equipos · Proyectos · Contacto</p><p>© {new Date().getFullYear()} Casyco</p><a href="#inicio">Volver arriba ↑</a></footer></section></main></div>}
