import HeroVideo from './components/HeroVideo';
import WhatsAppButton from './components/WhatsAppButton';
import MachineryCollage from './components/MachineryCollage';
import ColombiaBadge from './components/ColombiaBadge';
import SectionNavigation from './components/SectionNavigation';
import BrandsSection from './components/BrandsSection';
import{useEffect,useState}from'react';import{motion,useReducedMotion}from'framer-motion';import{ArrowRight,Check,Menu,X,Route,Factory,Building2}from'lucide-react';import constructionPhoto from'./assets/WhatsApp Image 2026-09-05 at 7.06.12 PM.jpeg';
import logo from './assets/Yellow_and_Black_Modern_Construction_Logo__1_-removebg-preview.png';
const Reveal=({children,delay=0,direction='left'}:{children:React.ReactNode,delay?:number,direction?:'left'|'right'})=>{const reduced=useReducedMotion();return <motion.div initial={reduced?false:{opacity:0,x:direction==='left'?-45:45}} whileInView={{opacity:1,x:0}} viewport={{once:false,amount:.1}} transition={{duration:reduced?0:.8,delay:reduced?0:delay,ease:[.2,.7,.2,1]}}>{children}</motion.div>};
const services=[['01','Movimiento de tierras','Excavación, nivelación y adecuación de terrenos para obras de cualquier escala.'],['02','Alquiler de maquinaria','Equipos confiables, disponibles con operador y respaldo técnico permanente.'],['03','Obras civiles','Ejecución coordinada para infraestructura, urbanismo y desarrollo industrial.']];
export default function Construction(){
const[menu,setMenu]=useState(false),[solid,setSolid]=useState(false),[notice,setNotice]=useState('Al continuar se abrirá tu aplicación de correo con la solicitud lista para enviar.');
useEffect(()=>{const update=()=>setSolid(window.scrollY>40);update();window.addEventListener('scroll',update,{passive:true});const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setMenu(false);document.querySelector<HTMLButtonElement>('.menuToggle')?.focus()}};document.addEventListener('keydown',escape);return()=>{window.removeEventListener('scroll',update);document.removeEventListener('keydown',escape)}},[]);
return <div className="cw"><WhatsAppButton/><SectionNavigation/><a className="skipLink" href="#inicio">Saltar al contenido</a><header className={solid||menu?'solid':''}><a className="cwLogo" href="#inicio" aria-label="CAS&CO, inicio"><img src={logo} alt="CAS&CO SAS" width="500" height="500"/></a><nav aria-label="Navegación principal"><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#equipo">Equipo</a></nav><a className="yellowBtn" href="#contacto">Hablemos de tu proyecto <ArrowRight/></a><ColombiaBadge/><button className="menuToggle" aria-label={menu?'Cerrar menú':'Abrir menú'} aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><nav id="mobile-menu" aria-label="Navegación móvil" className="cwMobile" style={menu?undefined:{display:'none'}} onClick={event=>{if((event.target as HTMLElement).closest('a'))setMenu(false)}}><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a><a href="#equipo">Equipo</a><a href="#contacto">Contacto</a></nav>
<main><section className="cwHero" id="inicio"><HeroVideo/><div className="heroMeta"><p>Construcción · minería · obras civiles</p></div><h1>Grandes obras.<br/><em>Un gran aliado.</em></h1><p className="heroDescription">La fuerza que tu proyecto necesita. Maquinaria pesada y un equipo comprometido con cada paso de tu obra.</p><div className="heroActions"><a className="yellowBtn" href="#maquinaria">Explora la maquinaria <ArrowRight/></a><a href="#contacto">Cotiza tu proyecto <ArrowRight aria-hidden="true"/></a></div><div className="heroBottom"><span>CAS&CO SAS / COLOMBIA</span><a href="#nosotros">Descubre lo que nos mueve ↓</a></div></section><div className="industryStrip"><span>Maquinaria pesada</span><span>Alquiler y venta</span><span>Asesoría técnica</span><span>Respaldo en cada obra</span></div>
<section className="cwIntro" id="nosotros"><Reveal><p className="overline">Quiénes somos</p><h2>Convertimos terreno,<br/>planos y visión en<br/><em>progreso real.</em></h2></Reveal><Reveal delay={.1} direction="right"><div><p>Somos una empresa de construcción y maquinaria pesada enfocada en ejecutar con precisión, seguridad y cumplimiento.</p><p>Desde la planeación hasta la entrega, coordinamos todos los recursos para que cada obra avance.</p><a href="#equipo">Conoce nuestro equipo <ArrowRight/></a></div></Reveal></section>
<section className="cwServices" id="servicios"><div className="sectionHead"><Reveal><p className="overline">Lo que hacemos</p><h2>Capacidad para construir.<br/><em>Respaldo para cumplir.</em></h2></Reveal><p>Soluciones integrales adaptadas al alcance, terreno y cronograma de tu proyecto.</p></div><div className="serviceRows">{services.map((s,i)=><Reveal key={i} delay={i*.08} direction={i%2===0?'left':'right'}><article><small>{s[0]}</small><h3>{s[1]}</h3><p>{s[2]}</p><a href="#contacto"><ArrowRight/></a></article></Reveal>)}</div></section>
<section className="cwFeature" id="maquinaria"><div className="featurePhoto"><MachineryCollage/></div><Reveal><div className="featureCopy"><p className="overline">Maquinaria + experiencia</p><h2>La fuerza correcta,<br/>en el momento correcto.</h2><p>Equipos inspeccionados, operadores experimentados y soporte técnico para mantener el ritmo de la obra.</p><ul><li><Check/>Disponibilidad según proyecto</li><li><Check/>Mantenimiento preventivo</li><li><Check/>Respuesta técnica en campo</li></ul><a className="yellowBtn" href="#contacto">Consultar maquinaria <ArrowRight/></a></div></Reveal></section>
<section className="cwProjects" id="proyectos"><Reveal><p className="overline">Trabajo reciente</p><h2>Proyectos que dejan<br/><em>una marca positiva.</em></h2></Reveal><div className="projectsGrid">{['Infraestructura vial','Plataforma industrial','Urbanismo y redes'].map((p,i)=><Reveal key={i} delay={i*.08} direction={i%2===0?'left':'right'}><article><div className="projectPhoto">{i===0?<Route aria-hidden="true"/>:i===1?<Factory aria-hidden="true"/>:<Building2 aria-hidden="true"/>}<span>{p}</span></div><div><small>0{i+1} · COLOMBIA</small><h3>{p}</h3><ArrowRight/></div></article></Reveal>)}</div></section>
<section className="cwStats" id="resultados"><Reveal><div><strong>15</strong><span>Años de<br/>experiencia</span></div></Reveal><Reveal><div><strong>120+</strong><span>Proyectos<br/>ejecutados</span></div></Reveal><Reveal><div><strong>98%</strong><span>Cumplimiento<br/>operativo</span></div></Reveal><Reveal><div><strong>24/7</strong><span>Soporte en<br/>campo</span></div></Reveal></section>
<BrandsSection/><section className="cwTeam" id="equipo"><Reveal><p className="overline">Nuestro equipo</p><h2>Personas que hacen<br/>que las cosas <em>pasen.</em></h2></Reveal><div className="teamPhoto"><img src={constructionPhoto} alt="Excavadoras Hitachi en el patio de maquinaria" loading="lazy"/></div></section>
<section className="cwContact" id="contacto"><Reveal><p className="overline">Hablemos</p><h2>¿Listo para empezar<br/><em>tu próximo proyecto?</em></h2><p>Cuéntanos qué necesitas. Nuestro equipo te ayudará a definir el siguiente paso.</p></Reveal><form onSubmit={event=>{event.preventDefault();const data=new FormData(event.currentTarget);const body=`Nombre: ${data.get('nombre')}\nCorreo: ${data.get('email')}\nTeléfono: ${data.get('telefono')}\nServicio: ${data.get('servicio')}\n\n${data.get('mensaje')}`;window.location.href=`mailto:proyectos@casyco.com?subject=${encodeURIComponent('Solicitud de cotización - '+data.get('servicio'))}&body=${encodeURIComponent(body)}`;setNotice('Solicitud preparada. Completa el envío en tu aplicación de correo. Si no se abre, escribe a proyectos@casyco.com.')}}><label>Nombre completo<input name="nombre" autoComplete="name" required placeholder="Tu nombre"/></label><label>Correo corporativo<input name="email" autoComplete="email" type="email" required placeholder="correo@empresa.com"/></label><label>Teléfono<input name="telefono" autoComplete="tel" type="tel" placeholder="+57"/></label><label>Servicio requerido<select name="servicio" required defaultValue=""><option value="" disabled>Selecciona un servicio</option><option>Movimiento de tierras</option><option>Alquiler de maquinaria</option><option>Obra civil</option></select></label><label className="full">Tu proyecto<textarea name="mensaje" required rows={4} placeholder="Ubicación, equipo y duración estimada"/></label><button className="yellowBtn" type="submit">Preparar correo <ArrowRight/></button><p className="formNote" role="status">{notice}</p></form></section></main>
<footer><a className="cwLogo" href="#inicio" aria-label="CAS&CO, inicio"><img src={logo} alt="CAS&CO SAS" width="500" height="500"/></a><p>Construimos hoy lo que mueve el mañana.</p><div><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#proyectos">Proyectos</a></div><small>© {new Date().getFullYear()} CAS&CO. Todos los derechos reservados.</small></footer></div>}
