import{useEffect,useRef,useState}from'react';import{motion,useScroll,useTransform}from'framer-motion';import{ArrowRight,ChevronDown,Clock,HardHat,Headphones,Menu,ShieldCheck,Truck,X}from'lucide-react';import rawMachine from'./assets/retroexcavadora-cutout.png';
const Fade=({children}:{children:React.ReactNode})=><motion.div initial={{opacity:0,y:35}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.2}} transition={{duration:.65}}>{children}</motion.div>;
const equipment=['Retroexcavadoras','Excavadoras','Cargadores','Compactadores'];
export default function Website(){const[menu,setMenu]=useState(false),[cutout,setCutout]=useState(''),track=useRef<HTMLElement>(null);const{scrollYProgress:p}=useScroll({target:track,offset:['start end','end start']}),{scrollYProgress:page}=useScroll(),carX=useTransform(p,[0,.5,1],['45vw','0vw','-28vw']),carY=useTransform(p,[0,.5,1],[80,0,-30]),gx=useTransform(page,[0,.05,.12,.2],['18vw','5vw','-18vw','-60vw']),gy=useTransform(page,[0,.08,.2],['20vh','4vh','12vh']),gs=useTransform(page,[0,.1,.2],[1,.75,.55]),go=useTransform(page,[0,.17,.2],[1,1,0]);useEffect(()=>{const im=new Image();im.src=rawMachine;im.onload=()=>{const c=document.createElement('canvas'),z=c.getContext('2d')!;c.width=im.width;c.height=im.height;z.drawImage(im,0,0);const d=z.getImageData(0,0,c.width,c.height),seen=new Uint8Array(c.width*c.height),q:number[]=[];for(let x=0;x<c.width;x++)q.push(x,(c.height-1)*c.width+x);for(let y=0;y<c.height;y++)q.push(y*c.width,y*c.width+c.width-1);while(q.length){const n=q.pop()!;if(seen[n])continue;seen[n]=1;const i=n*4,r=d.data[i],g=d.data[i+1],b=d.data[i+2];if(Math.max(r,g,b)-Math.min(r,g,b)>14||Math.min(r,g,b)<200)continue;d.data[i+3]=0;const x=n%c.width,y=Math.floor(n/c.width);if(x)q.push(n-1);if(x<c.width-1)q.push(n+1);if(y)q.push(n-c.width);if(y<c.height-1)q.push(n+c.width)}z.putImageData(d,0,0);setCutout(c.toDataURL())}},[]);return <>{cutout&&<motion.img className="globalMachine" src={cutout} alt="Retroexcavadora Casyco" style={{x:gx,y:gy,scale:gs,opacity:go}}/>}
<header><a className="wordmark" href="#inicio"><i>C</i><b>CASYCO</b><small>MAQUINARIA</small></a><nav><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#equipos">Equipos</a><a href="#proyectos">Proyectos</a></nav><a className="primary" href="#contacto">Cotizar ahora <ArrowRight/></a><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<nav className="drawer"><a href="#nosotros">Nosotros</a><a href="#servicios">Servicios</a><a href="#equipos">Equipos</a><a href="#contacto">Contacto</a></nav>}
<main><section className="cover" id="inicio"><div className="coverCopy"><p className="eyebrow">Soluciones para grandes proyectos</p><h1>Maquinaria que<br/>hace avanzar<br/><em>tu obra.</em></h1><p>Alquiler, operación y soporte técnico de maquinaria pesada con respuesta rápida y acompañamiento experto.</p><div><a className="primary" href="#contacto">Solicitar cotización <ArrowRight/></a><a className="plain" href="#servicios">Ver servicios</a></div></div><a className="down" href="#servicios"><ChevronDown/> Desliza para explorar</a></section>
<section className="quick" id="servicios">{[[Truck,'Alquiler de equipos','Flota disponible'],[HardHat,'Operación especializada','Personal certificado'],[Headphones,'Soporte en campo','Respuesta oportuna'],[ShieldCheck,'Equipos confiables','Inspección continua']].map(([Icon,t,d])=><Fade><article><Icon/><h3>{t as string}</h3><p>{d as string}</p><ArrowRight/></article></Fade>)}</section>
<section className="about" id="nosotros"><Fade><div className="photoPlaceholder">IMAGEN DE LA EMPRESA / PROYECTO</div></Fade><Fade><div className="copy"><p className="eyebrow">Más que maquinaria</p><h2>Un aliado que entiende el ritmo de tu obra.</h2><p>Coordinamos equipo, operador, logística y soporte para que puedas concentrarte en ejecutar. Cada solución parte de las condiciones reales de tu proyecto.</p><ul><li><ShieldCheck/>Mantenimiento e inspección permanente</li><li><Clock/>Disponibilidad y cumplimiento</li><li><Headphones/>Acompañamiento durante la operación</li></ul><a className="primary" href="#contacto">Conoce nuestra empresa <ArrowRight/></a></div></Fade></section>
<section className="scrollStory" ref={track}><div className="storySticky"><motion.div className="storyText" style={{opacity:useTransform(p,[0,.2,.75,1],[0,1,1,0])}}><p className="eyebrow">Potencia en movimiento</p><h2>Una máquina.<br/>Todo el respaldo.</h2><div className="specs"><span><b>4×4</b>Tracción</span><span><b>24/7</b>Soporte</span><span><b>100%</b>Respuesta</span></div></motion.div><motion.img className="scrollMachine" src={cutout||rawMachine} alt="Retroexcavadora en movimiento" style={{x:carX,y:carY}}/></div></section>
<section className="equipment" id="equipos"><Fade><div className="heading"><div><p className="eyebrow">Nuestra flota</p><h2>El equipo indicado para cada trabajo.</h2></div><p>Elige una categoría y encuentra la solución que tu proyecto necesita.</p></div></Fade><div className="equipmentGrid">{equipment.map((e,i)=><Fade><article><div className="photoPlaceholder">IMAGEN EQUIPO {i+1}</div><small>0{i+1}</small><h3>{e}</h3><p>Disponibilidad según proyecto y ubicación.</p><a href="#contacto">Consultar <ArrowRight/></a></article></Fade>)}</div></section>
<section className="how"><Fade><p className="eyebrow">Cómo funciona</p><h2>Simple, claro y sin detener tu obra.</h2></Fade><div>{[['01','Cuéntanos tu necesidad'],['02','Definimos la solución'],['03','Llevamos el equipo'],['04','Te acompañamos']].map((v,i)=><Fade><article><b>{v[0]}</b><i>{i+1}</i><h3>{v[1]}</h3><p>Revisamos alcance, ubicación, tiempos y condiciones operativas.</p></article></Fade>)}</div></section>
<section className="projects" id="proyectos"><Fade><p className="eyebrow">Experiencia comprobada</p><h2>Proyectos que hablan por nosotros.</h2></Fade><div className="projectCards">{['Infraestructura vial','Movimiento de tierras','Adecuación industrial'].map((e,i)=><Fade><article><div className="photoPlaceholder">IMAGEN PROYECTO {i+1}</div><p>Proyecto 0{i+1}</p><h3>{e}</h3><a href="#contacto">Ver proyecto <ArrowRight/></a></article></Fade>)}</div></section>
<section className="review"><Fade><div className="stars">★★★★★</div><blockquote>“Cumplieron con el equipo y los tiempos acordados. El soporte técnico durante la obra fue excelente.”</blockquote><p>Director de proyecto <span>· Infraestructura regional</span></p></Fade></section>
<section className="contactBox" id="contacto"><div><p className="eyebrow">Hablemos de tu proyecto</p><h2>¿Qué necesitas mover?</h2><p>Completa el formulario. Nuestro equipo te contactará para recomendarte el equipo adecuado.</p><p className="contactData">+57 300 000 0000<br/>proyectos@casyco.com<br/>Bogotá, Colombia</p></div><form><label>Nombre<input required placeholder="Tu nombre"/></label><label>Empresa<input placeholder="Tu empresa"/></label><label>Correo<input type="email" required placeholder="correo@empresa.com"/></label><label>Teléfono<input placeholder="+57"/></label><label className="full">Cuéntanos sobre la obra<textarea rows={4} placeholder="Ubicación, equipo y duración estimada"/></label><button className="primary">Enviar solicitud <ArrowRight/></button></form></section></main>
<footer><div className="wordmark"><i>C</i><b>CASYCO</b><small>MAQUINARIA</small></div><p>Maquinaria y respaldo para construir futuro.</p><div><a href="#servicios">Servicios</a><a href="#equipos">Equipos</a><a href="#contacto">Contacto</a></div><small>© {new Date().getFullYear()} Casyco. Todos los derechos reservados.</small></footer></>}
